package ru.iokhin.tm.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-06-03T10:44:36.547+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.tm.iokhin.ru/", name = "SessionEndpointBean")
@XmlSeeAlso({ObjectFactory.class})
public interface SessionEndpointBean {

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/SessionEndpointBean/createRequest", output = "http://endpoint.tm.iokhin.ru/SessionEndpointBean/createResponse")
    @RequestWrapper(localName = "create", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.CreateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.iokhin.tm.endpoint.Session create(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.String userId
    );

    @WebMethod
    @Action(input = "http://endpoint.tm.iokhin.ru/SessionEndpointBean/validateRequest", output = "http://endpoint.tm.iokhin.ru/SessionEndpointBean/validateResponse", fault = {@FaultAction(className = AuthException_Exception.class, value = "http://endpoint.tm.iokhin.ru/SessionEndpointBean/validate/Fault/AuthException")})
    @RequestWrapper(localName = "validate", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.Validate")
    @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://endpoint.tm.iokhin.ru/", className = "ru.iokhin.tm.endpoint.ValidateResponse")
    public void validate(
        @WebParam(name = "session", targetNamespace = "")
        ru.iokhin.tm.endpoint.Session session
    ) throws AuthException_Exception;
}
